[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "conversor-temperatura"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "kevinassimos", email = "kevin.assimos@acad.ufsm.br" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

[project.urls]
Documentation = "https://github.com/kevinassimos/conversor-temperatura#readme"
Issues = "https://github.com/kevinassimos/conversor-temperatura/issues"
Source = "https://github.com/kevinassimos/conversor-temperatura"

[tool.hatch.envs.default]
dependencies = [
    "ruff",
    "pytest",
    "sphinx"
]

[tool.hatch.envs.default.env-vars]
PYTHONPATH = "src"

[tool.hatch.version]
path = "src/conversor_temperatura/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/conversor_temperatura tests}"

[tool.coverage.run]
source_pkgs = ["conversor_temperatura", "tests"]
branch = true
parallel = true
omit = [
  "src/conversor_temperatura/__about__.py",
]

[tool.coverage.paths]
conversor_temperatura = ["src/conversor_temperatura", "*/conversor-temperatura/src/conversor_temperatura"]
tests = ["tests", "*/conversor-temperatura/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
